export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE'; 
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE'; 
export const SET_CURRENT_USER = 'SET_CURRENT_USER';


export const SET_CURRENT_BOTS = 'SET_CURRENT_BOTS';
export const SET_ACTIVE_BOT   = 'SET_ACTIVE_BOT';


export const SET_CURRENT_INTENTS = 'SET_CURRENT_INTENTS';
export const ADD_NEW_INTENT = 'ADD_NEW_INTENT';
export const REMOVE_INTENT  = 'REMOVE_INTENT';


export const SET_CURRENT_UTTERANCES = 'SET_CURRENT_UTTERANCES';
export const RESET_UTTERANCES = 'RESET_UTTERANCES';
export const APPEND_UTTERANCES = 'APPEND_UTTERANCES';
export const REMOVE_UTTERANCES = "REMOVE_UTTERANCES";


export const SET_CURRENT_RESPONSES = "SET_CURRENT_RESPONSES";
export const APPEND_RESPONSES = 'APPEND_RESPONSE';
export const RESET_RESPONSES = 'RESET_RESPONSE';
export const REMOVE_RESPONSES = 'REMOVE_RESPONSE';


export const SET_CURRENT_ENTITIES = "SET_CURRENT_ENTITIES";
export const ADD_NEW_ENTITY = "ADD_NEW_ENTITY";
export const REMOVE_ENTITY  = "REMOVE_ENTITY";


export const GET_EXAMPLES = 'GET_EXAMPLES';
export const ADD_EXAMPLES = 'ADD_EXAMPLES';
export const REMOVE_EXAMPLES = 'REMOVE_EXAMPLES';


export const ADD_SYNONYM = 'ADD_SYNONYM';
export const REMOVE_SYNONYM = 'REMOVE_SYNONYM';

export const SET_CURRENT_REPLY = 'SET_CURRENT_REPLY';
